name: Release Python package with pontos

on:
  pull_request:
    types: [closed]

jobs:
  build-and-release:
    env:
      GITHUB_USER: ${{ secrets.GREENBONE_BOT }}
      GITHUB_MAIL: ${{ secrets.GREENBONE_BOT_MAIL }}
      GITHUB_TOKEN: ${{ secrets.GREENBONE_BOT_TOKEN }}
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    name: Build and release with pontos
    # If the label 'make release' is set. If PR is closed because of an merge
    if: contains( github.event.pull_request.labels.*.name, 'make release') && github.event.pull_request.merged == true
    runs-on: 'ubuntu-latest'
    steps:
    - name: Release with release action
      uses: greenbone/actions/release@v1
      with:
        version: 3.8
        conventional-commits: true
        github-user: ${{ secrets.GREENBONE_BOT }}
        github-user-mail: ${{ secrets.GREENBONE_BOT_MAIL }}
        github-user-token: ${{ secrets.GREENBONE_BOT_TOKEN }}
        gpg-key: ${{ secrets.GPG_KEY }}
        gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
